name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17  # Set Java 15 here

      - name: Build with Maven
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        run: |
          heroku login -i
          heroku git:remote -a your-heroku-app-name
          git push heroku main
